services:
  - type: web
    name: file-upload-server
    env: node
    region: oregon  # Specify a region like oregon, frankfurt, singapore, etc.
    buildCommand: NODE_ENV=development npm install --only=dev && npm run build
    startCommand: npm start
    plan: free
    autoDeploy: true
    branch: main
    healthCheckPath: /
    envVars: []
